### ISSUE TITLE
Latest version seems to lint into multiline HTML comments despite html_elements: false

### ISSUE THREAD

**Issue by Ravlen** [DavidAnson/markdownlint#832] opened 2023-05-25 11:09 UTC
As the title says, we tried rolling out the latest version and noticed that this version is linting into multi-line HTML comments, ignoring our `html_elements: false` setting, at least for rule MD044.

This doesn't work:

- ![Screenshot 2023-05-25 at 20 03 33](https://github.com/DavidAnson/markdownlint/assets/36979740/6b5c0564-26c9-43a6-b5e6-f313a9f0d1bf)

This gets ignored as expected:

- ![Screenshot 2023-05-25 at 20 04 03](https://github.com/DavidAnson/markdownlint/assets/36979740/4ab14bd6-b5e6-47ed-860e-c8d1fc5bc96f)

It looks like it only works if the line either starts with `<!--` or ends with `-->`:

- ![Screenshot 2023-05-25 at 20 05 02](https://github.com/DavidAnson/markdownlint/assets/36979740/c7fbc073-3af3-4093-842c-8663988e95da)

**Comment by okalachev** [comment] 2023-05-28 11:45
Also have a I problem with this parameter.

Works for single line HTML, but doesn't work for multi-line:

<img width="344" alt="Screenshot 2023-05-28 at 14 45 29" src="https://github.com/DavidAnson/markdownlint/assets/1683279/18f25b89-0710-4421-8a0f-3c4f05fe3443">

**Comment by DavidAnson** [comment] 2023-05-29 02:48
@okalachev, OCR and attempting to reproduce your own example gives me two issues, not one. What am I missing?

https://dlaa.me/markdownlint/#%25m%23%20Issue%20832%0A%0A%3Ca%20href%3D%22https%3A%2F%2Fexample.org%22%3E%0A%3Cdiv%3E%3Ca%20href%3D%22https%3A%2F%2Fexample.org%22%3E%3C%2Fdiv%3E%0A%3Cdiv%3E%0A%20%20%3Ca%20href%3D%22https%3A%2F%2Fexample.org%22%3E%0A%3C%2Fdiv%3E%0A%0A%3C!--%20markdownlint-configure-file%20%7B%0A%20%20%22MD033%22%3A%20false%2C%0A%20%20%22MD044%22%3A%20%7B%0A%20%20%20%20%22html_elements%22%3A%20false%2C%0A%20%20%20%20%22names%22%3A%20%5B%0A%20%20%20%20%20%20%22HTTPS%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D%20--%3E%0A

**Comment by okalachev** [comment] 2023-05-29 03:18
@DavidAnson, sorry for using an image instead of text, but I wanted to emphasize the detected error.

Here is what I'm showing: https://dlaa.me/markdownlint/#%25m%23%20Issue%20832%0A%0A%3Ca%20href%3D%22https%3A%2F%2Fexample.org%22%3E%0A%0A%3Cdiv%3E%3Ca%20href%3D%22https%3A%2F%2Fexample.org%22%3E%3C%2Fdiv%3E%0A%0A%3Cdiv%3E%0A%20%20%3Ca%20href%3D%22https%3A%2F%2Fexample.org%22%3E%0A%3C%2Fdiv%3E%0A%0A%3C!--%20markdownlint-configure-file%20%7B%0A%20%20%22MD033%22%3A%20false%2C%0A%20%20%22MD044%22%3A%20%7B%0A%20%20%20%20%22html_elements%22%3A%20false%2C%0A%20%20%20%20%22names%22%3A%20%5B%0A%20%20%20%20%20%20%22HTTPS%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D%20--%3E%0A.

Two single-line HTMLs (OK), one multiline (not OK).

**Comment by DavidAnson** [comment] 2023-05-29 04:17
Your example shows the same behavior as mine. This difference is probably not important since the fix for both scenarios is probably the same. I'll have a look soon.

**Comment by DavidAnson** [comment] 2023-05-29 04:44
(Aha, the difference in samples is whether there are blank lines above/below the middle line.)

**Comment by DavidAnson** [comment] 2023-05-29 05:35
Where we're at:
@Ravlen, your issue is fixed by the commit above.
@okalachev, your issue has turned up other issues... :)

**Comment by Ravlen** [comment] 2023-05-29 05:37
@DavidAnson As always, you do wonderful work! I'd love to make the PRs to fix these myself, but I'm only smart enough to use your great tool, not help out with it 😅

**Comment by DavidAnson** [comment] 2023-05-29 05:41
@Ravlen :) Thanks! I try to make the rules as simple as possible, but some of them are almost absurdly tricky. Maybe if I were smarter, some of this would be more approachable!

**Comment by okalachev** [comment] 2023-05-29 05:59
Agreed about wonderful work, thanks to this tool we can keep the source code of our big documentation site clean and consistent.

But due to these MD044 issues with HTML I can't switch do the latest version unfortunately.

**Closed** 2023-06-02 03:47 UTC
Labels: bug, fixed in next
