### ISSUE TITLE
Support ignoring options like ESLint?

### ISSUE THREAD

**Issue by ybiquitous** [DavidAnson/markdownlint#103] opened 2018-01-25 06:54 UTC
Hi! I always use this awesome package! 😄 

I think that ESLint's ignoring options are very awesome, so will markdownlint support this feature?

- `--ignore-path`
- `--no-ignore`
- `--ignore-pattern`

```sh
$ eslint -h
...
Ignoring files:
  --ignore-path path::String     Specify path of ignore file
  --no-ignore                    Disable use of ignore files and patterns
  --ignore-pattern [String]      Pattern of files to ignore (in addition to those in .eslintignore)
...
```

See <https://eslint.org/docs/user-guide/command-line-interface#options>.

Thanks.

**Comment by DavidAnson** [comment] 2018-01-25 07:47
Thanks! This sounds like an issue for `markdownlint-cli`, and related to or a duplicate of https://github.com/igorshubovych/markdownlint-cli/issues/16 and https://github.com/igorshubovych/markdownlint-cli/issues/24. If you agree, please add any additional info there and I will close this issue.

**Comment by ybiquitous** [comment] 2018-01-25 08:01
@DavidAnson OK, I agree. Please close this. 👍

**Comment by DavidAnson** [comment] 2018-01-25 08:09
Cool. I will look at adding this soon.

**Closed by DavidAnson** 2018-01-25 08:09 UTC
Labels: question

**Comment by ybiquitous** [comment] 2018-02-01 01:27
@DavidAnson [`markdownlint-cli@0.7.0`](https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.7.0) now supports this feature! 🎉 
Thank you so much for your great works! 😄 👍
