### ISSUE TITLE
MD051/link-fragments false error with user-specified heading anchor

### ISSUE THREAD

**Issue by misterbisson** [DavidAnson/markdownlint#581] opened 2022-09-14 17:22 UTC
- Error message: `content/intro/use-cases/index.md:20:5 MD051/link-fragments Link fragments should be valid [Context: "[Personally identifiable information (PII)](#pii)"]`
- Offending line: `  - [Personally identifiable information (PII)](#pii)`
- Target heading: `## Personally identifiable information (PII) {#pii}`

The target heading uses common markdown syntax to specify the id/anchor string for a heading.

**Comment by nschonni** [comment] 2022-09-14 17:25
Duplicate of https://github.com/DavidAnson/markdownlint/issues/570 maybe

**Comment by DavidAnson** [comment] 2022-09-14 19:09
Agree this looks like a duplicate;  Gitiles syntax is not CommonMark. @misterbisson, I will close this, unless you disagree.

**Closed** 2022-10-18 04:51 UTC
Labels: question
