### ISSUE TITLE
Question: New MD051 warnings upgrading from v14 to v15

### ISSUE THREAD

**Issue by CodeBlanch** [DavidAnson/markdownlint#1118] opened 2024-02-01 21:04 UTC
Hey @DavidAnson!

When we bump from v14 to v15 we are getting new MD051 warnings: https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/7716090575/job/21032134820?pr=5290#step:3:13

The fragments seem fine from what I can gather. Is this expected?

/cc @alanwest

**Comment by DavidAnson** [comment] 2024-02-02 04:26
Okay, this isn't a bug in `markdownlint`.

Here's one of the "before" headings from your change: https://dlaa.me/markdownlint/#%25m%23%20Issue%201118%0A%0A%23%23%20ConventionalRouting%3A%20Area%20using%20area%3Aexists%2C%20default%20controller%2Faction%0A

Note that it renders weird - that's because `:exists` is treated as an inline Markdown directive which is newly supported in the latest release of `markdownlint`. You can read more here: https://github.com/micromark/micromark-extension-directive

Directives are for extending, so the tool doesn't know if a particular one is valid or not. If the parser sees valid directive syntax, it treats it as a directive. Which means the heading above doesn't say what it looks like it says and there's a mis-match so MD051 rightly triggers.

Now, I would have assumed a directive needed to be preceded by a space character, but I don't see that called out in the "spec": https://talk.commonmark.org/t/generic-directives-plugins-syntax/444

If you want to read that whole discussion, be my guest. If you find there's supposed to be a space, we can log that as an issue against the `micromark` code. But I don't see this as an open/closed issue there, so I suspect it is deliberate.

Your change to put the relevant text in an inline code span avoids the issue by taking the colon/text out of the normal flow.

Unless you feel otherwise, I will close this as "by design". Thanks for reporting it!

**Closed** 2024-02-25 22:07 UTC
Labels: question
