### ISSUE TITLE
Support `allowlist` option for MD040

### ISSUE THREAD

**Issue by chenxsan** [DavidAnson/markdownlint#608] opened 2022-10-16 04:25 UTC
While MD040 requires us to specify a language, it doesn't specify which languages we can use, which means we can use whatever we want as long as it's not an empty one.

But in the cases of syntax highlighting, tools like [refractor](https://github.com/wooorm/refractor#data) will throw an error when we feed it an unknown language. It would be great if we can configure MD040 with an `allowlist`.

E.g.,

```
"MD040": { "allowlist": ["js", "css", "html"] },
```

**Comment by nschonni** [comment] 2022-11-04 16:26
Duplicate of https://github.com/DavidAnson/markdownlint/issues/608

**Closed** 2022-12-28 01:35 UTC
Labels: enhancement, fixed in next
