### ISSUE TITLE
MD026 (Trailing punctuation in header) does not consider HTML Entities

### ISSUE THREAD

**Issue by MetaFight** [DavidAnson/markdownlint#98] opened 2017-12-13 13:38 UTC
If I want my header to use angular brackets then MD026 fires incorrectly.

Example:
```
### Building &lt;application&gt;
```

The trailing `;` of the Greater-Than HTML Entity gets interpreted as punctuation.  I guess HTML Entities should be resolved before MD026 runs.

**Comment by DavidAnson** [comment] 2017-12-13 17:25
I think this is a duplicate of #62. CommonMark lets you escape angle brackets with backslash: http://spec.commonmark.org/0.28/#backslash-escapes

**Comment by MetaFight** [comment] 2017-12-13 17:29
Ah, good catch.  I checked the open bugs for a duplicate but I didn't consider the closed bugs.  I'll use the slash-escape approach then.

Cheers.

**Closed** 2017-12-13 17:29 UTC
Labels: question
