### ISSUE TITLE
Use markdownlint wirth quarto ".qmd" - files

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [DavidAnson/markdownlint#1145] opened 2024-03-05 09:31 UTC
Hi,

is there a way to use this plugin on .qmd files? 
Quarto https://github.com/quarto-dev/quarto-cli is a scientific publishing system based on markdown which allows executing code in between the markdown elements. 
It would be absolutely awesome if we could make markdownlint work with quarto.

Example:
test.qmd

```
# This is just some markdown
and we expect markdownlint to mark this as missing a line in between
```

**Comment by DavidAnson** [comment] 2024-03-05 18:51
As a library, you can pass any file in and it will be linted. If you are using this library through one of the markdownlint CLIs, you can similarly specify "*.qmd". If you are using the VS Code markdownlint extension, you can tell Code to treat .qmd files as Markdown and they should automatically be linted.

**Comment by GitHubGeniusOverlord** [comment] 2024-03-06 08:29
Worked for me with the VS Code extension. It would be cool to mention this in the extensions documentation. Or possibly to set this property at installation time.

**Comment by GitHubGeniusOverlord** [comment] 2024-03-13 12:08
I have to correct: While VS Code can be taught to teach .qmd files as .md, this leads to the .qmd loosing its properties. For examples a cell in the .qmd cannot be run anymore. This renders this approach unusable at the moment.

**Comment by DavidAnson** [comment] 2024-03-13 14:47
As a request for linting non-Markdown files in the VS Code extension, this is a duplicate of: https://github.com/DavidAnson/vscode-markdownlint/issues/228

**Closed** 2024-03-13 14:48 UTC
Labels: question
