### ISSUE TITLE
Add rule to check relative links

### ISSUE THREAD

**Issue by koenigst** [DavidAnson/markdownlint#586] opened 2022-09-23 04:56 UTC
### Use case

* Check relative link to files
* Check anchors in relative linked files (this would be an extension to [`MD051`](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md051)).

### Example

Files:
```
contributing.md
image.png
readme.md
```

Content `readme.md`:
```
# Heading
![image](image.png)
[link to anchor](contributing.md#Heading)
```

### Details

The logic for discovering relative files could be similar to [textlint-rule-no-dead-link](https://github.com/textlint-rule/textlint-rule-no-dead-link#relative-link-resolution).

**Comment by vorburger** [comment] 2023-03-12 21:41
#121 seems related to / a duplicate of this? (TL;DR https://github.com/Divlo/markdownlint-rule-relative-links is a plugin, and https://github.com/tcort/markdown-link-check/ a separate alternative.)

**Comment by DavidAnson** [comment] 2023-03-12 23:26
Agree, I will close this. Please add any missing details to that issue.

**Closed** 2023-03-12 23:27 UTC
Labels: new rule
