### ISSUE TITLE
New rule: link simplification

### ISSUE THREAD

**Issue by mathbunnyru** [DavidAnson/markdownlint#399] opened 2021-05-22 21:23 UTC
A link like this `[https://github.com](https://github.com)` can be easily simplified to `<https://github.com>`.
This way it's less code duplication and it is easier to read.

**Comment by mathbunnyru** [comment] 2021-05-24 19:54
@DavidAnson could you please give me an example of the PR or commit, which adds a new feature similar to this one?
I will try to implement it, though I don't know Node.js at all (so it will take some time).

**Comment by DavidAnson** [comment] 2021-05-24 22:25
Here is the most recent one: https://github.com/DavidAnson/markdownlint/pull/224

There is a complicating factor here that there is a collection of link-related rule requests I would ultimately like to bundle into one rule. I do not blame you if you do not want to wade into that, but if you do I will probably be a little pickier than usual. Fair warning. :)

**Comment by mathbunnyru** [comment] 2021-05-24 22:27
Thanks for the warning 😂
I will take a look at what I can do.

**Comment by Marcono1234** [comment] 2023-05-28 13:30
For anyone looking to implement this, #753 contains a bit additional information and corner cases to consider.

**Comment by Marcono1234** [comment] 2023-11-12 18:23
@DavidAnson, will this be fixed by the new [rule `MD054`](https://github.com/DavidAnson/markdownlint/blob/next/doc/md054.md)?

Though if I see it correctly, that new rule is only about allowing / disallowing certain link styles. But if I understand the author of this issue here correctly, the suggestion was to enforce a link style (autolink) depending on the link content, and not generally.

Or will that be tracked in #753 in the future? (technically that issue is a duplicate of this one here, but it covers more cases, including reference links)

**Comment by DavidAnson** [comment] 2023-11-12 18:47
Agree this is more like 753. I expect to push changes that implement that tonight.

**Closed** 2023-11-14 05:22 UTC
Labels: fixed in next, new rule
